spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driver-class-name: org.h2.Driver
    username: sa
    password: password
logging:
  level:
    org.springframework.web: DEBUG